#set quote(block: true)

= Conclusions and Outlook <chap:conclusions_outlook>

== General conclusions

This thesis was motivated by a fundamental question: can federated learning be conducted in a truly decentralised manner? The initial intuition pointed toward blockchain as a natural substrate for decentralised coordination. However, a systematic survey of the state of the art revealed an existing paradigm — gossip learning — that already eliminates the central server. The problem, well-documented in the literature, is that gossip learning consistently underperforms federated learning in both convergence speed and final model accuracy, precisely because it lacks any form of structured aggregation.

This gap shaped the central research question of the thesis: _how can the efficiency of gossip learning be improved so as to approach federated learning, without sacrificing decentralisation?_ The answer, as argued throughout this work, lies not at the application layer but one level below, at the peer sampling layer.

The key insight is that peer sampling governs which nodes communicate with which, and therefore how information propagates across the system. By acting at this layer — elevating a dynamic subset of nodes to the role of hubs — it becomes possible to introduce a structured aggregation topology without relying on any pre-assigned coordinator or use-case-specific infrastructure. This is the contribution of the *Elevator* protocol. Elevator is a decentralised peer-to-peer overlay protocol that organises nodes through a lightweight, self-organising random election mechanism. Crucially, Elevator is application-agnostic: it provides a general-purpose structured overlay that any distributed algorithm can exploit.

The evaluation of Elevator rests on three complementary pillars. First, a theoretical analysis characterises the protocol's behaviour in terms of overlay properties — diameter, average shortest path length, and clustering coefficient — and derives analytical bounds on convergence and hub election dynamics. Second, these theoretical results are validated through large-scale simulations conducted on PeerSim, a peer-to-peer network simulator widely used and recognised by the research community. Third, a real implementation over TCP/IP confirms that the protocol behaves as predicted at the network level, bridging the gap between simulation and deployment. The consistency across all three levels of evaluation strengthens confidence in the correctness and robustness of the protocol.

This multi-level methodology did not come for free. Peer-to-peer networks with emergent hub structures of the kind introduced by Elevator are a novelty, and the research community has not converged on standard evaluation practices for such systems. A substantial methodological effort was therefore devoted to establishing appropriate scientific rigour: selecting and justifying the evaluation metrics, designing visualisations that faithfully represent the structural properties of the overlay, and adapting PeerSim — a simulator that is over twenty years old and was not designed with hub-based overlays in mind — to the requirements of this work. In particular, scaling simulations to networks of thousands or even hundreds of thousands of nodes, which is the operational target of a general-purpose peer-to-peer protocol, demanded significant engineering effort to make PeerSim tractable at that scale.

Building on Elevator, the *HEAL* protocol (Hub Enhanced Adaptive Learning) instantiates federated learning directly atop the structured overlay. Hubs serve as aggregators, and the inter-hub communication ensures that locally aggregated models are further reconciled across the network. This two-level aggregation scheme is the mechanism by which HEAL recovers the efficiency of federated learning while preserving decentralisation.

The evaluation of HEAL relies on simulation, but the machine learning component is not simulated: multiple real model architectures are trained on several benchmark datasets covering different learning tasks, ensuring that the measured accuracy figures reflect genuine model behaviour rather than approximations. The combination of diverse models, datasets, and task types provides strong evidence that the results are not artefacts of a particular experimental setup. Accuracy — a standard metric in the federated learning literature — is complemented by overlay topology metrics inherited from the Elevator evaluation, giving a joint view of network-level and learning-level performance. HEAL achieves competitive accuracy under fault-free conditions, and its resilience is confirmed under both crash failures and churn, owing to the redundant hub submission mechanism. Integrating the machine learning workload into large-scale peer-to-peer simulations further required adapting the simulation infrastructure to handle the additional computational and memory demands of real model training within a distributed event-driven framework.

The HEAL framework was subsequently extended in two directions. The *Lift* protocol augments Elevator with Byzantine fault tolerance, protecting the overlay construction process against malicious participants and thereby strengthening the security guarantees of the entire stack. The *FLAIR* protocol (Federated Learning with Adaptive Integrity-preserving Randomness) adapts HEAL to the constraints of physical wireless networks, where the overlay topology is no longer arbitrary but is shaped by radio range and interference. FLAIR draws inspiration from LEACH-style clustering to align the logical aggregation structure with the physical network layer, making the framework deployable in realistic WiFi environments. Its evaluation is conducted on ns-3, a network simulator widely recognised in the networking research community, which provides high-fidelity modelling of wireless channel conditions and MAC-layer behaviour. The use of a community-standard simulator ensures that the simulation results are reproducible and comparable to related work.

Taken together, the contributions of this thesis establish a coherent framework for decentralised, efficient, and resilient machine learning over peer-to-peer networks. The progression from gossip learning, through Elevator, to HEAL, Lift, and FLAIR constitutes a principled answer to the motivating question: structured aggregation can be achieved without centralisation, provided that the overlay layer is designed with that goal in mind.

#quote(quotes: true, attribution: [René Descartes, _Discours de la méthode_, 1637])[
  Diviser chacune des difficultés que j'examinerais en autant de parcelles
  qu'il se pourrait et qu'il serait requis pour les mieux résoudre.
]

== Outlook

The work presented in this thesis opens several research directions, spanning immediate extensions of the existing protocols to longer-term theoretical and applied challenges.

In the near term, two directions are already under active investigation. The first concerns the hub election mechanism in Elevator. In its current form, election is based on a random process, which ensures fairness but does not account for the heterogeneity of nodes in real deployments — nodes differ widely in computational capacity, memory, bandwidth, and availability. An ongoing line of work extends the election mechanism to incorporate node capability metrics, so that hubs are elected with a bias toward the most capable participants while preserving the decentralised nature of the process. Preliminary results are encouraging and suggest that capability-aware election yields overlays with better sustained aggregation throughput. The second near-term direction concerns data heterogeneity in HEAL. The current aggregation scheme does not account for statistical heterogeneity across nodes, which can cause the global model to drift away from the local data distributions of individual participants. Adapting the aggregation strategy — for instance through personalisation or locally-weighted aggregation — to mitigate this effect is a natural and pressing extension.

At medium term, two challenges stand out. The first is the integration of robustness against Byzantine attacks into HEAL itself. While Lift addresses Byzantine resilience at the overlay level, the learning layer remains vulnerable to poisoning attacks, in which malicious participants submit manipulated model updates, as well as to privacy attacks such as gradient inversion or membership inference. Equipping HEAL with defences against these threat models — whether through robust aggregation rules, differential privacy mechanisms, or secure aggregation protocols — is a necessary step toward deployment in adversarial environments. The second medium-term objective is a large-scale real-world deployment of Elevator and HEAL on a peer-to-peer network comprising hundreds of thousands of users. Such a deployment would validate the scalability assumptions made in the simulation studies and expose practical challenges — churn patterns, network heterogeneity, hardware diversity — that are difficult to reproduce faithfully in simulation.

In the longer term, three directions define a broader research programme. First, the scope of HEAL is currently limited to supervised learning tasks; extending the framework to unsupervised learning and reinforcement learning would significantly broaden its applicability, particularly for settings where labelled data is scarce or where agents must learn from interaction rather than from a fixed dataset. Second, HEAL operates under the horizontal federated learning assumption, where all participants share the same feature space. Adapting the framework to vertical federated learning — where different participants hold different features of the same instances — raises fundamentally different challenges in terms of aggregation, communication, and privacy, and would open the framework to a wider class of collaborative learning scenarios. Third, and perhaps most foundationally, a rigorous theoretical analysis of HEAL's convergence properties remains an open problem. Establishing convergence guarantees under realistic assumptions — partial participation, heterogeneous data, network dynamics — would place the empirical results on a firmer theoretical footing and provide actionable guidance for the design of future protocols in this family.

#quote(quotes: true, attribution: [Karl Popper])[
  Our knowledge can only be finite, while our ignorance must necessarily be infinite.
]